<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\MuscleGroup;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $g = fn ($name) => MuscleGroup::where('name', $name)->firstOrFail()->id;

        // Format: [name, muscle_group, equipment_type, difficulty, weight_unit, description, how_to]
        $exercises = [

            // ==================== DADA ====================
            // Gym - Barbell
            ['Barbell Bench Press', 'Dada', 'barbell', 'menengah', 'kg',
             'Gerakan wajib untuk membangun massa dan kekuatan dada secara keseluruhan. Compound movement terbaik untuk dada.',
             'Berbaring di bench, grip selebar bahu. Turunkan bar ke dada bawah, siku 45–75°. Dorong ke atas dengan ledakan. Pastikan punggung sedikit melengkung alami, kaki menapak.'],
            ['Incline Barbell Bench Press', 'Dada', 'barbell', 'menengah', 'kg',
             'Versi incline dari bench press untuk melatih bagian atas dada (upper chest). Bench diset 30–45°.',
             'Set bench 30–45°. Turunkan bar ke bagian atas dada / pectoralis mayor. Dorong ke atas. Fokus squeeze di bagian atas dada di puncak gerakan.'],
            ['Cable Fly', 'Dada', 'cable', 'menengah', 'kg',
             'Gerakan isolasi dada menggunakan cable untuk constant tension sepanjang range of motion.',
             'Set pulley di atas kepala, berdiri di tengah. Bawa kedua pegangan ke depan dan bawah seperti memeluk pohon besar. Squeeze dada di titik temu.'],
            ['Pec Deck / Butterfly Machine', 'Dada', 'mesin_gym', 'pemula', 'kg',
             'Mesin isolasi dada yang aman untuk pemula, tidak butuh stabilizer. Cocok sebagai finisher.',
             'Duduk tegak, siku 90° di pad. Bawa kedua arm ke tengah, squeeze dada di puncak. Kembali perlahan, jangan sampai bahu terlalu meregang ke belakang.'],
            ['Chest Dip', 'Dada', 'bodyweight', 'menengah', 'kg',
             'Compound movement untuk dada bawah dan triceps. Badan miring ke depan untuk fokus ke dada.',
             'Pegang parallel bars, condongkan badan 15–30° ke depan. Turunkan hingga bahu sedikit di bawah siku. Dorong kembali. Di gym bisa ditambah beban (belt/dumbbell).'],
            // Dumbbell
            ['Dumbbell Bench Press', 'Dada', 'dumbell', 'menengah', 'kg',
             'Alternatif bench press yang memberi lebih banyak range of motion dan keseimbangan otot dada.',
             'Berbaring di bench atau lantai, tekan dumbbell ke atas dari posisi setinggi dada. Turunkan perlahan dengan siku 45–75°.'],
            ['Dumbbell Incline Press', 'Dada', 'dumbell', 'menengah', 'kg',
             'Melatih upper chest dengan dumbbell. Bench diset 30–45°.',
             'Set bench 30–45°. Tekan dumbbell ke atas dari setinggi bahu atas. Squeeze upper chest di atas.'],
            ['Dumbbell Floor Press', 'Dada', 'dumbell', 'pemula', 'kg',
             'Versi aman bench press di lantai. Cocok untuk home workout tanpa bench.',
             'Berbaring di lantai, lutut ditekuk. Pegang dumbbell di sisi dada, dorong ke atas. Siku menyentuh lantai di titik bawah.'],
            ['Dumbbell Fly', 'Dada', 'dumbell', 'menengah', 'kg',
             'Gerakan isolasi untuk meregang dan membentuk dada bagian luar. Fokus stretch di bawah.',
             'Berbaring, rentangkan dumbbell ke samping dengan siku sedikit ditekuk. Satukan di atas dada seperti gerakan memeluk. Jangan kunci siku.'],
            // Resistance Band
            ['Resistance Band Chest Press', 'Dada', 'resistance_band', 'pemula', 'band_level',
             'Latihan dada dengan band, bisa dilakukan di mana saja. Cocok sebagai pengganti bench press.',
             'Ikat band di belakang tubuh atau tiang setinggi dada. Dorong kedua pegangan ke depan hingga lengan lurus, tahan, kembali perlahan.'],
            ['Resistance Band Fly', 'Dada', 'resistance_band', 'pemula', 'band_level',
             'Gerakan fly dengan band untuk isolasi dada. Constant tension cocok untuk pump dada.',
             'Pegang ujung band dari belakang. Bawa kedua tangan ke depan seperti memeluk. Squeeze dada di tengah.'],
            // Bodyweight
            ['Push-Up', 'Dada', 'bodyweight', 'pemula', 'kg',
             'Gerakan fundamental bodyweight untuk dada, bahu, dan triceps. Bisa dilakukan di mana saja.',
             'Posisi plank, tangan selebar bahu atau sedikit lebih lebar. Turunkan dada ke lantai menjaga badan lurus, dorong kembali. Jangan biarkan pinggul turun/naik.'],
            ['Wide Push-Up', 'Dada', 'bodyweight', 'pemula', 'kg',
             'Variasi push-up dengan tangan lebih lebar untuk fokus ke bagian tengah dan luar dada.',
             'Posisi push-up, tangan 1,5x lebar bahu. Turunkan dada lurus ke bawah di antara tangan. Siku membuka ke samping lebih lebar.'],
            ['Diamond Push-Up', 'Dada', 'bodyweight', 'menengah', 'kg',
             'Tangan membentuk diamond/segitiga, fokus ke inner chest dan triceps.',
             'Tangan berdekatan di bawah dada membentuk bentuk berlian. Turunkan dada ke arah tangan, siku flare ke belakang lebih banyak. Lebih sulit dari push-up biasa.'],
            ['Decline Push-Up', 'Dada', 'bodyweight', 'menengah', 'kg',
             'Kaki lebih tinggi dari tangan untuk melatih upper chest seperti incline press.',
             'Kaki di atas kursi/bangku, tangan di lantai. Turunkan dada ke arah lantai. Lebih berat karena distribusi beban ke atas.'],
            ['Archer Push-Up', 'Dada', 'bodyweight', 'lanjutan', 'kg',
             'Unilateral push-up untuk ketidakseimbangan otot dan intensitas lebih tinggi.',
             'Tangan lebar, saat turun geser berat ke satu sisi sambil meluruskan tangan satunya. Gantian. Butuh kekuatan dan koordinasi tinggi.'],

            // ==================== PUNGGUNG ====================
            // Gym
            ['Barbell Bent-Over Row', 'Punggung', 'barbell', 'menengah', 'kg',
             'Gerakan compound kunci untuk punggung tebal. Melatih lat, rhomboid, dan trap sekaligus.',
             'Bungkukkan badan 45–70°, punggung lurus. Tarik bar ke arah navel/perut bawah. Rapatkan tulang belikat di puncak. Turunkan terkontrol.'],
            ['T-Bar Row', 'Punggung', 'barbell', 'menengah', 'kg',
             'Variasi row dengan T-Bar untuk fokus ke punggung tengah (rhomboid, mid trap).',
             'Kaki mengangkang di atas T-bar, pegang handle. Bungkuk dan tarik ke arah dada. Jaga punggung lurus dan kepala netral.'],
            ['Lat Pulldown', 'Punggung', 'mesin_gym', 'pemula', 'kg',
             'Gerakan terbaik untuk melebarkan lat. Alternatif pull-up untuk pemula atau yang belum bisa pull-up.',
             'Duduk, grip selebar bahu atau lebih. Tarik bar ke dada atas sambil buka dada dan sedikit recline. Squeeze lat di bawah. Kembali perlahan.'],
            ['Seated Cable Row', 'Punggung', 'cable', 'pemula', 'kg',
             'Horizontal row dengan cable untuk punggung tengah. Constant tension dan aman untuk postur.',
             'Duduk dengan kaki di footplate, tarik handle ke perut sambil rapatkan tulang belikat. Kembali dengan kontrol, biarkan tulang belikat stretch di depan.'],
            ['Face Pull', 'Punggung', 'cable', 'pemula', 'kg',
             'Wajib untuk kesehatan bahu dan postur. Melatih rear delt dan rotator cuff yang sering diabaikan.',
             'Set pulley setinggi wajah, gunakan rope. Tarik ke arah wajah sambil buka tangan ke luar (external rotation). Squeeze shoulder blades. Gerakan lambat dan terkontrol.'],
            ['Straight Arm Pulldown', 'Punggung', 'cable', 'menengah', 'kg',
             'Isolasi lat yang bagus. Lengan tetap lurus sepanjang gerakan untuk fokus ke lat.',
             'Berdiri menghadap cable, pegang bar dengan lengan lurus sedikit di atas kepala. Bawa tangan lurus ke bawah ke pinggul, squeeze lat. Kembali perlahan.'],
            // Dumbbell
            ['Single-Arm Dumbbell Row', 'Punggung', 'dumbell', 'pemula', 'kg',
             'Row satu tangan dengan dumbbell. Memungkinkan range of motion penuh dan beban lebih berat.',
             'Lutut dan tangan satu sisi di bench (atau berdiri bungkuk). Tarik dumbbell ke pinggang sambil jaga punggung lurus. Squeeze lat di atas.'],
            ['Dumbbell Bent-Over Row', 'Punggung', 'dumbell', 'menengah', 'kg',
             'Row dua tangan dengan dumbbell untuk punggung keseluruhan.',
             'Bungkuk 45–70°, tarik kedua dumbbell ke perut bawah secara bersamaan. Rapatkan tulang belikat di puncak.'],
            ['Dumbbell Deadlift', 'Punggung', 'dumbell', 'menengah', 'kg',
             'Deadlift dengan dumbbell cocok untuk rumah. Melatih punggung bawah, glute, dan hamstring.',
             'Dumbbell di depan paha. Tekuk pinggul ke belakang (hip hinge) dengan punggung lurus, turunkan ke mid-shin. Dorong pinggul ke depan untuk berdiri.'],
            // Resistance Band
            ['Resistance Band Row', 'Punggung', 'resistance_band', 'pemula', 'band_level',
             'Row dengan band untuk punggung. Bisa dilakukan di rumah dengan mengikat band ke tiang.',
             'Ikat band di tiang setinggi dada atau lebih rendah. Tarik pegangan ke perut sambil rapatkan tulang belikat. Kembali terkontrol.'],
            ['Resistance Band Face Pull', 'Punggung', 'resistance_band', 'pemula', 'band_level',
             'Face pull dengan band untuk kesehatan bahu dan rear delt.',
             'Ikat band setinggi wajah. Tarik ke arah wajah sambil buka tangan ke luar. Squeeze shoulder blades.'],
            ['Resistance Band Pull-Apart', 'Punggung', 'resistance_band', 'pemula', 'band_level',
             'Gerakan sederhana tapi sangat efektif untuk postur dan upper back. Bisa dilakukan kapan saja.',
             'Pegang band di depan dada selebar bahu. Tarik ke kedua sisi sampai band menyentuh dada, rapatkan tulang belikat. Kembali perlahan.'],
            // Calisthenics / Bodyweight
            ['Pull-Up', 'Punggung', 'pull_up_bar', 'menengah', 'kg',
             'Raja latihan punggung. Grip pronasi (telapak menjauhi wajah). Melatih lat, bicep, dan rhomboid.',
             'Gantung di bar, grip selebar bahu atau lebih. Tarik tubuh ke atas hingga dagu melewati bar. Turunkan penuh. Hindari kipping kecuali untuk latihan spesifik.'],
            ['Chin-Up', 'Punggung', 'pull_up_bar', 'menengah', 'kg',
             'Mirip pull-up dengan grip supinasi (telapak menghadap wajah). Lebih menekankan bicep.',
             'Gantung dengan telapak menghadap wajah, grip selebar bahu. Tarik ke atas hingga dagu di atas bar. Kontrol turunnya.'],
            ['Wide-Grip Pull-Up', 'Punggung', 'pull_up_bar', 'lanjutan', 'kg',
             'Grip lebih lebar dari bahu untuk isolasi lat lebih dalam dan memperlebar upper back.',
             'Grip lebih lebar dari bahu, telapak menjauhi wajah. Tarik ke atas. Lebih sulit karena grip lebar mengurangi keterlibatan bicep.'],
            ['Inverted Row', 'Punggung', 'bodyweight', 'pemula', 'kg',
             'Row menggunakan berat badan sendiri. Cocok sebagai latihan punggung awal sebelum pull-up.',
             'Tidur di bawah meja atau bar rendah, pegang dengan telapak menghadap atau menjauhi. Tarik dada ke arah bar sambil jaga badan lurus.'],
            ['Superman', 'Punggung', 'bodyweight', 'pemula', 'kg',
             'Gerakan untuk punggung bawah (erector spinae). Sederhana tapi efektif untuk mencegah nyeri pinggang.',
             'Tengkurap di lantai, lengan lurus ke depan. Angkat dada, lengan, dan kaki dari lantai secara bersamaan. Tahan 2–3 detik. Kembali.'],

            // ==================== BAHU ====================
            // Gym
            ['Barbell Overhead Press', 'Bahu', 'barbell', 'menengah', 'kg',
             'Compound movement utama bahu. Melatih seluruh bahu + triceps + core stabilizer.',
             'Berdiri atau duduk, bar di depan bahu. Dorong ke atas hingga lengan lurus di atas kepala. Kunci siku. Turunkan ke dagu/hidung. Jaga core tight.'],
            ['Machine Shoulder Press', 'Bahu', 'mesin_gym', 'pemula', 'kg',
             'Versi mesin dari shoulder press. Lebih aman untuk pemula karena jalur gerak terpandu.',
             'Duduk tegak, atur tinggi seat. Dorong handle ke atas hingga lengan hampir lurus. Turunkan terkontrol. Jangan bouncing di bawah.'],
            ['Cable Lateral Raise', 'Bahu', 'cable', 'pemula', 'kg',
             'Lateral raise dengan cable memberikan constant tension sepanjang gerakan, lebih efektif untuk deltoid lateral.',
             'Berdiri samping cable, pegang handle dengan tangan jauh. Angkat ke samping hingga sejajar bahu. Turunkan perlahan. Boleh condong sedikit ke arah cable.'],
            ['Cable Front Raise', 'Bahu', 'cable', 'pemula', 'kg',
             'Melatih anterior deltoid (depan bahu) dengan cable.',
             'Berdiri menghadap berlawanan dari cable. Tarik handle ke depan hingga setinggi bahu. Turunkan terkontrol.'],
            ['Reverse Pec Deck', 'Bahu', 'mesin_gym', 'pemula', 'kg',
             'Melatih rear deltoid (belakang bahu) yang sering diabaikan. Penting untuk postur dan keseimbangan bahu.',
             'Duduk menghadap ke bantal mesin, pegang handle dengan lengan hampir lurus. Buka ke samping belakang. Squeeze rear delt. Kembali terkontrol.'],
            // Dumbbell
            ['Dumbbell Shoulder Press', 'Bahu', 'dumbell', 'menengah', 'kg',
             'Overhead press dengan dumbbell. Range of motion lebih bebas dan melatih stabilizer lebih banyak.',
             'Duduk atau berdiri, dumbbell setinggi bahu. Dorong ke atas secara bersamaan. Jangan benturkan di atas.'],
            ['Dumbbell Lateral Raise', 'Bahu', 'dumbell', 'pemula', 'kg',
             'Gerakan wajib untuk melebarkan bahu. Fokus ke deltoid lateral.',
             'Berdiri tegak, angkat dumbbell ke samping dengan siku sedikit ditekuk. Berhenti sejajar bahu. Turunkan perlahan. Jangan pakai momentum.'],
            ['Dumbbell Front Raise', 'Bahu', 'dumbell', 'pemula', 'kg',
             'Melatih bahu depan (anterior deltoid).',
             'Berdiri tegak, angkat satu atau dua dumbbell ke depan hingga setinggi bahu. Turunkan perlahan.'],
            ['Dumbbell Rear Delt Fly', 'Bahu', 'dumbell', 'pemula', 'kg',
             'Melatih rear delt dan upper back. Penting untuk postur tegak.',
             'Bungkuk 45–70° atau duduk membungkuk. Angkat dumbbell ke samping dengan siku sedikit ditekuk. Squeeze shoulder blades di atas.'],
            ['Arnold Press', 'Bahu', 'dumbell', 'menengah', 'kg',
             'Overhead press dinamis yang melatih semua 3 kepala deltoid dalam satu gerakan. Diciptakan Arnold Schwarzenegger.',
             'Mulai dengan telapak menghadap wajah di depan bahu. Saat mendorong ke atas, putar tangan sehingga telapak menghadap ke depan di atas. Balik saat turun.'],
            // Resistance Band
            ['Resistance Band Shoulder Press', 'Bahu', 'resistance_band', 'pemula', 'band_level',
             'Overhead press menggunakan band. Injak band dengan kaki, dorong ke atas.',
             'Injak band dengan kedua kaki selebar bahu. Pegang ujung band setinggi bahu, telapak menghadap depan. Dorong ke atas hingga lengan lurus.'],
            ['Resistance Band Lateral Raise', 'Bahu', 'resistance_band', 'pemula', 'band_level',
             'Lateral raise dengan band untuk bahu samping.',
             'Injak band, pegang ujung di kedua tangan. Angkat ke samping hingga sejajar bahu. Turunkan terkontrol.'],
            // Bodyweight
            ['Pike Push-Up', 'Bahu', 'bodyweight', 'menengah', 'kg',
             'Push-up versi V-shape untuk melatih bahu dan triceps. Mirip overhead press dengan berat badan.',
             'Posisi push-up, angkat pinggul ke atas hingga membentuk huruf V terbalik. Turunkan kepala ke arah lantai di antara tangan, dorong kembali.'],
            ['Handstand Push-Up', 'Bahu', 'bodyweight', 'lanjutan', 'kg',
             'Overhead press dengan berat badan penuh. Salah satu gerakan bahu terkuat di kalistenik.',
             'Lakukan handstand dengan kaki bersandar di dinding. Turunkan kepala ke lantai perlahan, dorong kembali. Mulai dengan partial range jika belum kuat.'],

            // ==================== LENGAN ====================
            // Bicep - Gym
            ['Barbell Bicep Curl', 'Lengan', 'barbell', 'pemula', 'kg',
             'Gerakan utama bicep dengan beban terberat. Membangun ukuran dan kekuatan bicep.',
             'Berdiri tegak, bar dengan underhand grip. Tekuk siku sambil jaga siku di samping badan. Squeeze bicep di atas. Turunkan penuh.'],
            ['EZ-Bar Curl', 'Lengan', 'barbell', 'pemula', 'kg',
             'Curl dengan EZ-bar yang lebih ramah untuk pergelangan tangan. Efektif untuk bicep dan brachialis.',
             'Grip EZ-bar di bagian angled/miring. Curl ke atas sambil jaga siku statis. Squeeze di puncak.'],
            ['Cable Curl', 'Lengan', 'cable', 'pemula', 'kg',
             'Curl dengan cable untuk constant tension. Bagus untuk pump dan finisher bicep.',
             'Berdiri menghadap cable bawah. Curl ke atas sambil jaga siku tidak bergerak. Bisa pakai rope untuk neutral grip atau bar untuk supinated.'],
            ['Preacher Curl', 'Lengan', 'mesin_gym', 'pemula', 'kg',
             'Curl di preacher bench untuk isolasi penuh bicep. Menghilangkan kemungkinan cheat.',
             'Duduk di preacher bench, lengan atas di pad. Curl ke atas hanya menggunakan bicep, turunkan penuh sambil jaga ketegangan.'],
            // Bicep - Dumbbell
            ['Dumbbell Bicep Curl', 'Lengan', 'dumbell', 'pemula', 'kg',
             'Curl klasik dengan dumbbell. Bisa bergantian (alternatif) atau bersamaan.',
             'Berdiri tegak, tekuk siku mengangkat dumbbell ke bahu. Turunkan perlahan. Siku tidak bergerak ke depan/belakang.'],
            ['Hammer Curl', 'Lengan', 'dumbell', 'pemula', 'kg',
             'Curl dengan grip netral (telapak menghadap dalam). Melatih brachialis dan brachioradialis untuk ketebalan lengan.',
             'Grip dumbbell seperti memegang palu. Curl ke atas dengan telapak selalu menghadap ke dalam. Tidak ada rotasi pergelangan tangan.'],
            ['Concentration Curl', 'Lengan', 'dumbell', 'pemula', 'kg',
             'Curl isolasi maksimal untuk puncak bicep (bicep peak). Siku menempel di paha dalam.',
             'Duduk di bangku, siku menempel di dalam paha. Curl perlahan ke atas, squeeze penuh di puncak. Turunkan penuh.'],
            // Tricep - Gym
            ['Cable Tricep Pushdown', 'Lengan', 'cable', 'pemula', 'kg',
             'Gerakan utama tricep dengan cable. Constant tension dan aman untuk sendi. Bisa pakai rope, bar, atau V-bar.',
             'Berdiri menghadap cable, siku ditekuk 90° di samping badan. Dorong handle ke bawah hingga lengan lurus. Squeeze tricep. Kembali terkontrol.'],
            ['Skull Crusher', 'Lengan', 'barbell', 'menengah', 'kg',
             'Latihan tricep dengan berbaring. Sangat efektif untuk ukuran dan kekuatan tricep.',
             'Berbaring di bench, pegang EZ-bar/dumbbell di atas dada dengan lengan lurus. Tekuk siku menurunkan bar ke dahi. Dorong kembali. Siku tidak boleh flare.'],
            // Tricep - Dumbbell
            ['Dumbbell Tricep Kickback', 'Lengan', 'dumbell', 'pemula', 'kg',
             'Isolasi tricep dengan dumbbell. Efektif untuk membentuk bagian belakang lengan.',
             'Bungkuk, lengan atas sejajar badan. Luruskan lengan ke belakang hingga lurus. Squeeze tricep. Kembali terkontrol.'],
            ['Dumbbell Overhead Tricep Extension', 'Lengan', 'dumbell', 'pemula', 'kg',
             'Melatih long head tricep yang terbesar. Bisa dilakukan duduk atau berdiri.',
             'Pegang satu dumbbell dengan kedua tangan di atas kepala. Tekuk siku menurunkan dumbbell ke belakang kepala. Luruskan kembali.'],
            // Bodyweight Arms
            ['Dips', 'Lengan', 'bodyweight', 'menengah', 'kg',
             'Compound movement tricep dan dada bawah. Sangat efektif untuk masa tricep.',
             'Pegang parallel bars atau kursi, badan tegak (untuk tricep focus). Turunkan siku ke 90°. Dorong kembali. Di gym bisa ditambah beban.'],
            ['Resistance Band Bicep Curl', 'Lengan', 'resistance_band', 'pemula', 'band_level',
             'Curl dengan band. Cocok untuk home workout, constant tension baik untuk bicep.',
             'Injak band di tengah dengan kedua kaki. Curl ke atas seperti dumbbell curl. Pertahankan tension sepanjang gerakan.'],
            ['Resistance Band Tricep Pushdown', 'Lengan', 'resistance_band', 'pemula', 'band_level',
             'Pushdown tricep dengan band. Ikat band di atas pintu atau tiang.',
             'Ikat band setinggi kepala atau lebih tinggi. Pegang ujung, siku di samping badan. Dorong ke bawah hingga lurus. Kembali terkontrol.'],

            // ==================== PERUT / CORE ====================
            // Gym
            ['Cable Crunch', 'Perut / Core', 'cable', 'pemula', 'kg',
             'Crunch dengan beban dari cable. Memungkinkan overload progresif yang jelas untuk core.',
             'Berlutut menghadap cable, pegang rope di atas kepala. Crunch ke bawah dengan membulatkan punggung, bukan hanya menekuk pinggul. Squeeze abs di bawah.'],
            ['Hanging Leg Raise', 'Perut / Core', 'pull_up_bar', 'menengah', 'kg',
             'Salah satu gerakan core terbaik. Melatih lower abs dan hip flexor. Gantung di pull-up bar.',
             'Gantung di bar. Angkat kaki lurus atau ditekuk ke atas hingga sejajar pinggul atau lebih. Turunkan terkontrol tanpa swing. Ketatkan abs sepanjang gerakan.'],
            ['Ab Wheel Rollout', 'Perut / Core', 'lainnya', 'menengah', 'kg',
             'Salah satu latihan core terberat dan terbaik. Melatih seluruh core termasuk anti-extension.',
             'Berlutut, pegang ab wheel di bawah bahu. Roll ke depan sambil jaga core tight dan punggung lurus. Kembali ke start dengan mengontraksikan abs. Mulai dari partial range.'],
            ['Cable Woodchopper', 'Perut / Core', 'cable', 'menengah', 'kg',
             'Gerakan rotasi untuk oblique. Sangat efektif untuk membentuk pinggang.',
             'Set cable di atas. Tarik diagonal dari atas ke bawah melintasi tubuh sambil memutar pinggang. Kaki tegak. Kembali terkontrol.'],
            ['Pallof Press', 'Perut / Core', 'cable', 'menengah', 'kg',
             'Anti-rotation core exercise. Sangat efektif untuk kekuatan core fungsional dan mencegah cedera punggung.',
             'Berdiri menyamping ke cable. Pegang handle di depan dada. Dorong lurus ke depan, tahan, kembali. Core harus melawan rotasi dari cable.'],
            // Dumbbell Core
            ['Dumbbell Russian Twist', 'Perut / Core', 'dumbell', 'pemula', 'kg',
             'Latihan oblique klasik. Memutar tubuh untuk membentuk pinggang samping.',
             'Duduk dengan lutut ditekuk dan badan sedikit miring ke belakang. Pegang dumbbell, putar badan ke kanan dan kiri secara bergantian. Jaga kaki terangkat untuk intensitas lebih.'],
            ['Dumbbell Side Bend', 'Perut / Core', 'dumbell', 'pemula', 'kg',
             'Melatih oblique samping. Sederhana tapi efektif untuk pinggang.',
             'Berdiri, pegang satu dumbbell di satu tangan. Condongkan ke samping sejauh mungkin, kembali ke atas. Jaga pinggul statis.'],
            // Resistance Band Core
            ['Resistance Band Woodchopper', 'Perut / Core', 'resistance_band', 'menengah', 'band_level',
             'Woodchopper dengan band sebagai pengganti cable. Efektif untuk oblique.',
             'Ikat band di titik tinggi di samping. Tarik diagonal ke bawah sambil memutar pinggang. Kembali terkontrol.'],
            ['Resistance Band Pallof Press', 'Perut / Core', 'resistance_band', 'menengah', 'band_level',
             'Anti-rotation exercise dengan band. Baik untuk core stability.',
             'Ikat band setinggi dada di samping. Berdiri menyamping, dorong lurus ke depan dan tahan. Cegah tubuh berputar.'],
            // Bodyweight Core
            ['Plank', 'Perut / Core', 'bodyweight', 'pemula', 'kg',
             'Gerakan core fundamental. Melatih seluruh core secara isometrik. McGill Big 3 exercise.',
             'Posisi push-up bertumpu di lengan bawah. Jaga badan lurus dari kepala ke tumit. Tarik navel ke spine. Tahan posisi. Mulai 20–30 detik, progress durasi.'],
            ['Side Plank', 'Perut / Core', 'bodyweight', 'pemula', 'kg',
             'Melatih oblique dan lateral core. McGill Big 3 exercise. Penting untuk mencegah nyeri punggung.',
             'Berbaring menyamping, bertumpu di lengan bawah dan kaki tumpukan. Angkat pinggul hingga badan lurus dari kepala ke kaki. Tahan.'],
            ['Crunch', 'Perut / Core', 'bodyweight', 'pemula', 'kg',
             'Gerakan dasar untuk upper abs. Tidak perlu peralatan.',
             'Berbaring, lutut ditekuk. Angkat bahu dari lantai dengan membulatkan punggung atas, jangan angkat full sit-up. Tangan di belakang kepala tanpa menarik leher.'],
            ['Reverse Crunch', 'Perut / Core', 'bodyweight', 'pemula', 'kg',
             'Melatih lower abs dengan mengangkat pinggul, bukan badan atas.',
             'Berbaring, kaki sejajar lantai. Angkat pinggul dari lantai sambil menarik lutut ke dada. Kembali terkontrol. Jaga lower back tetap di lantai.'],
            ['Leg Raise', 'Perut / Core', 'bodyweight', 'menengah', 'kg',
             'Lower abs yang lebih berat dari reverse crunch. Kaki tetap lurus sepanjang gerakan.',
             'Berbaring, kaki lurus. Angkat kaki ke atas hingga 90° sambil jaga lower back di lantai (bisa pakai tangan di bawah glute). Turunkan perlahan tanpa menyentuh lantai.'],
            ['Bicycle Crunch', 'Perut / Core', 'bodyweight', 'pemula', 'kg',
             'Salah satu gerakan core dengan aktivasi abs tertinggi menurut penelitian ACE. Melatih oblique dan rectus abdominis.',
             'Berbaring, tangan di belakang kepala. Angkat bahu dan kaki. Bawa siku kanan ke lutut kiri bersamaan sambil luruskan kaki kanan. Bergantian seperti mengayuh sepeda.'],
            ['Mountain Climber', 'Perut / Core', 'bodyweight', 'pemula', 'kg',
             'Cardio + core exercise. Melatih core dinamis dan meningkatkan heart rate.',
             'Posisi plank, tarik lutut bergantian ke arah dada secepat mungkin. Jaga pinggul tidak naik. Bisa lambat (untuk core) atau cepat (untuk cardio).'],
            ['V-Up', 'Perut / Core', 'bodyweight', 'menengah', 'kg',
             'Gerakan full abs yang menantang. Tangan dan kaki bertemu di atas secara bersamaan.',
             'Berbaring lurus. Angkat kaki dan badan secara bersamaan membentuk huruf V. Jangkau kaki dengan tangan. Kembali terkontrol.'],
            ['Hollow Body Hold', 'Perut / Core', 'bodyweight', 'menengah', 'kg',
             'Posisi fundamental kalistenik. Melatih seluruh anterior core dengan intens.',
             'Berbaring, angkat bahu dan kaki sedikit dari lantai. Tekan lower back ke lantai. Tahan posisi. Mulai dengan lutut ditekuk, progress ke kaki lurus dan lengan di atas.'],
            ['Dead Bug', 'Perut / Core', 'bodyweight', 'pemula', 'kg',
             'Anti-extension core exercise yang aman untuk punggung. Bagus untuk pemula dan rehabilitasi.',
             'Berbaring, lengan lurus ke atas, lutut 90° di udara. Turunkan lengan kanan dan kaki kiri secara bersamaan (hampir menyentuh lantai) sambil jaga lower back flat. Kembali, bergantian.'],

            // ==================== BOKONG ====================
            // Gym
            ['Barbell Hip Thrust', 'Bokong', 'barbell', 'menengah', 'kg',
             'Gerakan #1 untuk glute berdasarkan penelitian EMG (Contreras et al., 2015). Aktivasi gluteus maximus 2x lebih tinggi dari squat.',
             'Bahu bersandar di bench, bar di atas pinggul (pakai pad). Dorong pinggul ke atas hingga badan lurus, squeeze glute penuh di atas selama 1–2 detik. Turunkan terkontrol.'],
            ['Smith Machine Hip Thrust', 'Bokong', 'mesin_gym', 'pemula', 'kg',
             'Hip thrust di smith machine. Lebih aman dan mudah untuk mengatur beban secara mandiri.',
             'Setup sama seperti barbell hip thrust tapi gunakan bar di smith machine. Mudah di-rack dan un-rack sendiri.'],
            ['Cable Kickback', 'Bokong', 'cable', 'pemula', 'kg',
             'Isolasi glute dengan cable. Baik untuk membentuk bagian bawah glute.',
             'Pasang ankle cuff di kaki, berdiri menghadap cable. Tendang kaki ke belakang dengan glute. Jaga badan stabil, jangan berayun.'],
            // Dumbbell
            ['Dumbbell Glute Bridge', 'Bokong', 'dumbell', 'pemula', 'kg',
             'Glute bridge dengan dumbbell di pinggul. Dasar sebelum hip thrust. Cocok untuk rumah.',
             'Berbaring telentang, lutut ditekuk. Letakkan dumbbell di atas pinggul. Dorong pinggul ke atas, squeeze glute di puncak. Turunkan.'],
            ['Dumbbell Hip Thrust', 'Bokong', 'dumbell', 'menengah', 'kg',
             'Hip thrust dengan dumbbell. Bisa dilakukan di rumah menggunakan sofa atau bangku.',
             'Bahu di sofa/bangku, dumbbell di pinggul. Dorong pinggul ke atas, squeeze glute di puncak. Sama dengan barbell tapi beban lebih ringan.'],
            ['Dumbbell Bulgarian Split Squat', 'Bokong', 'dumbell', 'lanjutan', 'kg',
             'Salah satu gerakan unilateral terbaik untuk glute dan quad. Intensitas tinggi dengan beban relatif ringan.',
             'Kaki belakang di atas bangku. Pegang dumbbell di kedua tangan. Turunkan lutut depan ke dekat lantai, dorong kembali. Fokus ke heel kaki depan untuk glute lebih banyak.'],
            ['Dumbbell Romanian Deadlift', 'Bokong', 'dumbell', 'menengah', 'kg',
             'RDL dengan dumbbell untuk hamstring dan glute. Tidak perlu menyentuh lantai.',
             'Berdiri dengan dumbbell di depan paha. Tekuk pinggul ke belakang (bukan lutut) sambil turunkan dumbbell ke mid-shin. Punggung lurus. Dorong pinggul ke depan untuk berdiri.'],
            // Resistance Band
            ['Resistance Band Hip Thrust', 'Bokong', 'resistance_band', 'pemula', 'band_level',
             'Hip thrust dengan resistance band. Sangat efektif untuk rumah. Lingkarkan di atas pinggul.',
             'Lingkarkan band di atas pinggul dan kaitkan ke bawah (bangku atau kaki lain). Berbaring, dorong pinggul ke atas melawan tahanan band. Squeeze glute penuh.'],
            ['Resistance Band Lateral Walk', 'Bokong', 'resistance_band', 'pemula', 'band_level',
             'Melatih glute medius (bokong samping). Membentuk lekukan samping bokong. Ikat band di atas lutut.',
             'Lingkarkan band di atas lutut. Posisi setengah squat. Langkahkan kaki ke samping 10–15 langkah, kembali ke arah lain. Jaga lutut tidak collapse ke dalam.'],
            ['Resistance Band Kickback', 'Bokong', 'resistance_band', 'pemula', 'band_level',
             'Isolasi glute dengan menendang kaki ke belakang melawan band.',
             'Kaitkan band di pergelangan kaki dan tiang. Berlutut atau berdiri. Tendang kaki ke belakang dengan squeeze glute. Jaga lutut lurus di belakang.'],
            ['Resistance Band Clamshell', 'Bokong', 'resistance_band', 'pemula', 'band_level',
             'Aktivasi glute medius terbaik menurut penelitian. Cocok untuk pemanasan atau rehabilitasi.',
             'Berbaring menyamping, lutut ditekuk 90°. Band di atas lutut. Buka lutut atas seperti clamshell sambil jaga kaki menempel. Squeeze glute medius di atas.'],
            // Bodyweight
            ['Glute Bridge', 'Bokong', 'bodyweight', 'pemula', 'kg',
             'Versi bodyweight dari hip thrust. Sangat baik untuk aktivasi glute pemula dan pemanasan.',
             'Berbaring telentang, lutut ditekuk, kaki flat di lantai. Dorong pinggul ke atas hingga badan lurus, squeeze glute 2 detik. Turunkan.'],
            ['Donkey Kick', 'Bokong', 'bodyweight', 'pemula', 'kg',
             'Isolasi glute dengan posisi merangkak. Populer untuk home workout glute.',
             'Posisi merangkak (all-fours). Angkat satu kaki ke belakang atas dengan lutut 90°. Squeeze glute di atas. Jaga pinggul level, tidak berputar.'],
            ['Fire Hydrant', 'Bokong', 'bodyweight', 'pemula', 'kg',
             'Melatih glute medius. Abduksi pinggul dari posisi merangkak.',
             'Posisi merangkak. Angkat lutut ke samping setinggi pinggul. Jaga sudut lutut 90°. Kembali terkontrol. Jangan biarkan pinggul miring.'],

            // ==================== KAKI ====================
            // Gym - Barbell
            ['Barbell Back Squat', 'Kaki', 'barbell', 'menengah', 'kg',
             'Raja latihan kaki. Compound movement terbaik untuk quad, hamstring, glute, dan core. Wajib ada di program gym.',
             'Bar di atas trap, grip nyaman. Squat ke bawah dengan lutut mengikuti arah jari kaki. Turunkan hingga paha sejajar lantai atau lebih dalam. Dorong dari heel.'],
            ['Barbell Romanian Deadlift', 'Kaki', 'barbell', 'menengah', 'kg',
             'Terbaik untuk hamstring. Hip hinge dengan bar tetap di depan kaki (tidak ke lantai).',
             'Berdiri, pegang bar. Hip hinge ke belakang sambil turunkan bar di dekat kaki ke mid-shin. Jaga punggung lurus dan bar dekat badan. Dorong pinggul ke depan untuk berdiri.'],
            ['Leg Press', 'Kaki', 'mesin_gym', 'pemula', 'kg',
             'Squat dengan mesin. Aman untuk pemula dan orang dengan masalah keseimbangan. Bisa sangat overloaded.',
             'Atur footplate di tengah. Dorong platform ke atas hingga lutut hampir lurus. Turunkan terkontrol. Jangan unlock lutut sepenuhnya di atas.'],
            ['Leg Curl', 'Kaki', 'mesin_gym', 'pemula', 'kg',
             'Isolasi hamstring menggunakan mesin. Penting untuk keseimbangan quad-hamstring.',
             'Berbaring di leg curl machine, pad di atas Achilles. Curl kaki ke atas/belakang. Squeeze hamstring di puncak. Kembali penuh.'],
            ['Leg Extension', 'Kaki', 'mesin_gym', 'pemula', 'kg',
             'Isolasi quad menggunakan mesin. Cocok sebagai finisher atau untuk rehabilitasi lutut.',
             'Duduk di leg extension, pad di atas kaki. Luruskan kaki ke depan, squeeze quad. Kembali terkontrol. Hati-hati untuk yang punya masalah lutut.'],
            ['Hack Squat', 'Kaki', 'mesin_gym', 'menengah', 'kg',
             'Squat di mesin hack squat. Lebih fokus ke quad karena punggung bersandar.',
             'Berdiri di platform hack squat, bahu di pad. Squat ke bawah hingga paha sejajar atau lebih dalam. Dorong kembali.'],
            // Dumbbell
            ['Dumbbell Goblet Squat', 'Kaki', 'dumbell', 'pemula', 'kg',
             'Squat sederhana dengan satu dumbbell di depan dada. Cocok untuk pemula dan home workout.',
             'Pegang dumbbell vertikal di depan dada. Kaki selebar bahu. Squat dalam dengan punggung tegak. Siku di dalam lutut di bawah.'],
            ['Dumbbell Lunges', 'Kaki', 'dumbell', 'pemula', 'kg',
             'Lunges dengan dumbbell untuk quad dan glute. Juga melatih keseimbangan.',
             'Pegang dumbbell di kedua tangan. Langkahkan satu kaki ke depan, turunkan lutut belakang ke dekat lantai. Dorong kembali ke posisi awal.'],
            ['Dumbbell Romanian Deadlift', 'Kaki', 'dumbell', 'menengah', 'kg',
             'RDL dengan dumbbell untuk hamstring dan glute bawah.',
             'Berdiri, dumbbell di depan paha. Hip hinge ke belakang sambil turunkan dumbbell. Jaga punggung lurus. Dorong pinggul ke depan untuk berdiri.'],
            ['Dumbbell Step-Up', 'Kaki', 'dumbell', 'pemula', 'kg',
             'Melatih quad dan glute unilateral. Naik turun dari bangku/step sambil pegang dumbbell.',
             'Pegang dumbbell, naiki bangku dengan satu kaki. Dorong dari tumit kaki atas, bawa kaki lain ke atas. Turun terkontrol.'],
            ['Dumbbell Calf Raise', 'Kaki', 'dumbell', 'pemula', 'kg',
             'Melatih gastrocnemius dan soleus (betis). Penting untuk athletic performance.',
             'Berdiri dengan dumbbell di kedua tangan. Angkat tumit setinggi mungkin. Tahan di atas 1–2 detik. Turunkan perlahan hingga tumit di bawah level telapak kaki (jika di step).'],
            // Resistance Band
            ['Resistance Band Squat', 'Kaki', 'resistance_band', 'pemula', 'band_level',
             'Squat dengan band untuk menambah resistensi. Injak band, pegang di bahu.',
             'Injak band dengan kedua kaki, pegang ujung di bahu. Squat seperti biasa. Band memberi resistensi lebih berat di bagian atas.'],
            ['Resistance Band Romanian Deadlift', 'Kaki', 'resistance_band', 'pemula', 'band_level',
             'RDL dengan band. Cocok sebagai home workout untuk hamstring.',
             'Injak band di tengah. Pegang ujung band dengan kedua tangan. Hip hinge ke belakang sambil turunkan tangan ke mid-shin. Kembali.'],
            // Bodyweight
            ['Bodyweight Squat', 'Kaki', 'bodyweight', 'pemula', 'kg',
             'Dasar dari semua gerakan squat. Wajib dikuasai sebelum menambah beban.',
             'Kaki selebar bahu, jari sedikit keluar. Squat ke bawah hingga paha sejajar lantai, lutut mengikuti arah jari. Jaga punggung tegak.'],
            ['Jump Squat', 'Kaki', 'bodyweight', 'menengah', 'kg',
             'Plyometric squat untuk daya ledak (power) dan membakar kalori lebih banyak.',
             'Squat ke bawah lalu melompat setinggi mungkin. Daratkan dengan lembut (soft landing) kembali ke posisi squat.'],
            ['Walking Lunge', 'Kaki', 'bodyweight', 'pemula', 'kg',
             'Lunge bergerak ke depan. Melatih seluruh kaki dan koordinasi. Bisa ditambah dumbbell.',
             'Langkah lebar ke depan, turunkan lutut belakang. Langkah kaki belakang ke depan untuk lunges berikutnya. Jaga badan tegak.'],
            ['Wall Sit', 'Kaki', 'bodyweight', 'pemula', 'kg',
             'Isometrik quad yang efektif. Sangat baik untuk endurance otot dan daya tahan.',
             'Bersandar di dinding dengan lutut 90°. Paha sejajar lantai. Tahan selama mungkin. Progress dengan memperlama durasi.'],
            ['Pistol Squat', 'Kaki', 'bodyweight', 'lanjutan', 'kg',
             'Single-leg squat. Salah satu gerakan kalistenik paling menantang untuk kaki.',
             'Berdiri satu kaki, kaki lain lurus ke depan. Squat ke bawah sambil jaga kaki lain terangkat. Gunakan tangan untuk keseimbangan di awal.'],
            ['Nordic Hamstring Curl', 'Kaki', 'bodyweight', 'lanjutan', 'kg',
             'Latihan hamstring eccentric terbaik. Terbukti mengurangi risiko cedera hamstring.',
             'Berlutut, kaki dikunci di bawah sesuatu yang berat. Turunkan badan ke depan sepelan mungkin dengan hamstring (jangan collapse). Gunakan tangan untuk push-up di bawah.'],
            ['Bodyweight Calf Raise', 'Kaki', 'bodyweight', 'pemula', 'kg',
             'Calf raise tanpa beban. Bisa dilakukan di step untuk range of motion lebih dalam.',
             'Berdiri di tepi step atau lantai. Angkat tumit setinggi mungkin. Tahan, turunkan perlahan. Bisa satu atau dua kaki.'],

            // ==================== FULL BODY ====================
            ['Barbell Deadlift', 'Full Body', 'barbell', 'menengah', 'kg',
             'The king of all exercises. Melatih hampir semua otot tubuh. Terbaik untuk kekuatan keseluruhan dan massa.',
             'Kaki selebar pinggul di bawah bar. Hip hinge, pegang bar. Punggung lurus, dada terbuka. Dorong lantai sambil tarik bar ke atas. Lockout di atas dengan glutr squeeze.'],
            ['Barbell Clean and Press', 'Full Body', 'barbell', 'lanjutan', 'kg',
             'Gerakan olimpik yang melatih seluruh tubuh dalam satu rangkaian. Power, strength, dan koordinasi.',
             'Pull bar dari lantai dengan explosive hip extension (clean ke bahu), kemudian press ke atas kepala. Gerakan teknis, pelajari dengan pelatih atau video detail.'],
            ['Barbell Thruster', 'Full Body', 'barbell', 'lanjutan', 'kg',
             'Kombinasi front squat + overhead press dalam satu gerakan. Salah satu gerakan paling melelahkan tapi efektif.',
             'Bar di depan bahu (front rack). Squat ke bawah, lalu saat berdiri gunakan momentum untuk press bar ke atas. Harus ada transfer energi dari kaki ke lengan.'],
            ['Dumbbell Thruster', 'Full Body', 'dumbell', 'menengah', 'kg',
             'Versi dumbbell dari thruster. Cocok untuk home workout full body yang intense.',
             'Dumbbell di bahu. Squat, lalu transfer momentum ke atas untuk press dumbbell. Satu gerakan menyambung antara squat dan press.'],
            ['Dumbbell Clean and Press', 'Full Body', 'dumbell', 'menengah', 'kg',
             'Versi dumbbell dari clean and press. Melatih seluruh tubuh dengan satu gerakan dinamis.',
             'Dumbbell di lantai. Lift explosive ke bahu (clean), kemudian press ke atas. Lebih mudah dipelajari dibanding barbell clean.'],
            ['Turkish Get-Up', 'Full Body', 'dumbell', 'lanjutan', 'kg',
             'Gerakan fungsional kompleks yang melatih mobilitas, stabilitas, dan kekuatan keseluruhan tubuh.',
             'Berbaring pegang dumbbell di atas dengan satu tangan. Berdiri sambil jaga dumbbell tetap di atas sepanjang waktu menggunakan serangkaian gerakan bertahap. Gerakan lambat dan terkontrol.'],
            ['Resistance Band Full Body Squat to Press', 'Full Body', 'resistance_band', 'pemula', 'band_level',
             'Kombinasi squat + press dengan band. Full body dengan alat minimal.',
             'Injak band, pegang ujung di bahu. Squat ke bawah, saat berdiri dorong ujung band ke atas kepala. Satu gerakan menyambung.'],
            ['Burpee', 'Full Body', 'bodyweight', 'menengah', 'kg',
             'Gerakan full body paling efektif untuk membakar kalori. Cardio + strength dalam satu gerakan.',
             'Dari berdiri, squat lalu tangan ke lantai, loncat kaki ke belakang (push-up position), push-up (opsional), loncat kaki kembali, lompat ke atas dengan tangan di atas kepala.'],
            ['Bear Crawl', 'Full Body', 'bodyweight', 'pemula', 'kg',
             'Full body movement untuk core, bahu, dan kaki. Sangat baik untuk anak-anak dan dewasa.',
             'Posisi merangkak dengan lutut sedikit di atas lantai. Bergerak ke depan dengan gerakan berlawanan (tangan kanan + kaki kiri bersamaan). Jaga punggung lurus.'],
        ];

        foreach ($exercises as $e) {
            $slug = str()->slug($e[0]);
            Exercise::updateOrCreate(
                ['slug' => $slug],
                [
                    'muscle_group_id'    => $g($e[1]),
                    'name'               => $e[0],
                    'slug'               => $slug,
                    'equipment_type'     => $e[2],
                    'difficulty'         => $e[3],
                    'weight_unit_default'=> $e[4],
                    'description'        => $e[5],
                    'how_to'             => $e[6],
                    'is_active'          => true,
                ]
            );
        }
    }
}
